### PR TITLE
Replace zdharma repos with existing ones in zdharma-continuum

### PR DESCRIPTION
**Pull request by vtta**
Avoid installation from deleted repos.
This is only a partial modification, further changes are needed when all deleted repos are available under zdharma-continuum.

### CODE REVIEW

**Comment by vtta** [comment]
Todo list
- [x] zdharma/zsh-diff-so-fancy
- [x] zdharma/zflai
- [x] zdharma/zsh-unique-id

**Comment by luong-komorebi** [comment]
Thank you so much, so far so good. Keep up the awesome job

**Comment by luong-komorebi** [comment]
It would be helpful if you can notify me when to merge this. I would idealy wait for all the forks to be available to merge

**Comment by luong-komorebi** [comment]
zsh-unique-id is really hard to find 😭

**Comment by vtta** [comment]
Sure, I will look out for this one and post when I get a copy. 😁

**Comment by ryaminal** [comment]
i vote we merge this while we get the other pieces put in place. not like this breaks anything anymore than it already is.

**Comment by luong-komorebi** [comment]
@vtta The source code for zsh unique id has been uploaded

**Comment by vtta** [comment]
@luong-komorebi  @ryaminal updated and ok to merge 🥳

**Comment by ryaminal** [comment]
Thanks all. You are doing a great thing. I'll try and contribute instead of just being a leech.

**Pull request merged**
